#get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '[$directory$git_branch$git_commit](bold green)$character'

[character]
success_symbol = '[\$](bold green) '
error_symbol = '[\$](bold red) '

[cmd_duration]
min_time = 5000
format = 'Took [$duration](bold yellow) '
